
## Schedule

Essentials

- January 24: Syllabus, installing R/Rstudio/git
- January 31: Projects and Rmarkdown intro
    - [ ] set up project
    - [ ] explain why
    - [ ] R script, run simple commands
    - [ ] Build an Rmarkdown (html, then tinytex)
    - [ ] 
- February 7: R basics and Tidyverse philosophy
- February 14: data manipulation/pipes (order depending on data choice)
- February 21: ggplot
- February 28: regression and model output

What they don't teach you (pt 1): real data, workflow

- March 6: reading, cleaning, joining
    - dta, fwf, RDS, Rdata
    - nasty string characters
    - join state data
- March 13: tidying data (aka "shaping")
- March 20: **BREAK**
- March 27: TeX math, smart Rmd (opts_chunk, inline, english)
- April 3: Git and Github
    - <http://www.win-vector.com/blog/2020/03/version-control-is-a-time-machine-that-translates-common-hindsight-into-valuable-foresight/>

What they don't teach you (pt 2): marketable skills

- April 10: Intermediate git (branches, flow, large data)
    - data: LFS, submodules
- April 17: functional programming (apply, anonymous functions, purrr)
- April 24: causal inference (parametric)
- May 1: industry tools, predictive modeling (null distributions, bootstrapping, cross-validation) causal inference


<!-- other?

- [ ] manipulation
    - abv/below avg ideology w/in state?
- [ ] Tidying
- [ ] Reading data 
- [ ] Tidying data 
- [ ] Baller graphics 
- [ ] Apply functions, anonymous functions, and purrr
- [ ] estimating models and model output
- [ ] causal inference
- [ ] git
 -->
